### PR TITLE
Attempt to add support for CTD abbreviations

### PR DESCRIPTION
**Pull request by kimrutherford**
Refs pombase/canto#2807

### CODE REVIEW

**Comment by manulera** [comment]
Hi @kimrutherford, that grammar is for the alleles, not the modifications. I will explain in more detail in the next PR. I am almost done with the fix. @ValWood I am using these:

https://github.com/pombase/pombase-config/blob/65a136e8978182935f0bd67d547850cba3a1269a/website/pombase_v2_config.json#L7069-L7073

but I don't think they are correct. For example, T1582 does not exist.

**Comment by ValWood** [comment]
it looks like the T4 and the S7 lines are identical residues

"CTD_T4": "T1584,T1591,T1598,T1605,T1612,T1619,T1626,T1615,T1640,T1647,T1654,T1661,T1663,T1675,T1682,T1689,T1696,T1703,T1710,T1717,T1723,T1731,T1738,T1745,T1752",

  "CTD_S7":
 "S1584,S1591,S1598,S1605,S1612,S1619,S1626,S1615,S1640,S1647,S1654,S1661,S1668,S1675,S1682 S1689,S1696,S1703,S1710,S1717,S1724,S1731,S1738,S1745,S1752"

I will check what I did wrong tomorrow.

**Comment by ValWood** [comment]
corrected @kimrutherford  you will need to fix modifications allele display etc. Sorry about this!

"CTD_T4": "T1581,T1588,T1595,T1602,T1609,T1616,T1623,T1630,T1637,T1644, T1651,T1658,T1665,T1672,T1679,T1686,T1693,T1700,T1707,T1714,T1721,T1728,T1735,T1742,T1749",

**Comment by kimrutherford** [comment]
> you will need to fix modifications allele display

I've changed the configuration so it should be fixed on Sunday morning.

**Comment by manulera** [comment]
CTD_S5 is still wrong (T1582 still there)

**Comment by ValWood** [comment]
@kimrutherford  @manulera  what do I need to do here?
Is there anything for me to fix.

**Comment by kimrutherford** [comment]
> Is there anything for me to fix.

I don't think there is anything for you to do.

**Comment by manulera** [comment]
Replaced by #115

**Pull request closed without merging**
